### ISSUE TITLE
Travis-ci: build is failing on AMD64

### ISSUE THREAD

**Issue by sanjaymsh** [kenhys/fcitx-imlist#1]
Hi,

I am enabling ppc64le build on travis but before that, build is failing on AMD64 itself with below error:

"/bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c fcitx-imlist '/usr/local/bin'
/usr/bin/install: cannot create regular file ‘/usr/local/bin/fcitx-imlist’: Permission denied
make[2]: *** [install-binPROGRAMS] Error 1
make[2]: Leaving directory `/home/travis/build/sanjaymsh/fcitx-imlist/src'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/travis/build/sanjaymsh/fcitx-imlist/src'
make: *** [install-recursive] Error 1
The command "./autogen.sh && ./configure && make && make install" exited with 2.
Done. Your build exited with 1."

The full log can be tracked here https://travis-ci.com/github/sanjaymsh/fcitx-imlist/builds/188602974

Please have a look on this.

Thanks !!

**Comment by kenhys** [comment]
@sanjaymsh 
Thanks, I've fixed it.

https://travis-ci.com/github/kenhys/fcitx-imlist

**Comment by sanjaymsh** [comment]
Thanks !!
